version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: presentation_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: presentations
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: Europe/Budapest
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --event-scheduler=ON
    ports:
      - "3307:3306" # kívül 3307, belül 3306
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro

volumes:
  db_data:
